# Generated by Django 3.2.18 on 2024-05-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(default="", max_length=250),
        ),
    ]
