# Generated by Django 3.2.18 on 2024-05-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0003_auto_20240524_0655"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
