# Generated by Django 3.2.18 on 2024-06-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0004_alter_user_telephone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactUs",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
    ]
