# Generated by Django 3.2.18 on 2023-12-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("process", "Processing"),
                ],
                default="Processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("rejected", "Rejected"),
                    ("draft", "Draft"),
                    ("disabled", "Disabled"),
                    ("in_review", "In Review"),
                    ("published", "Published"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(
                choices=[
                    ("3", "★★★✩✩"),
                    ("5", "★★★★★"),
                    ("2", "★★✩✩✩"),
                    ("4", "★★★★✩"),
                    ("1", "★✩✩✩✩"),
                ],
                default=None,
            ),
        ),
    ]
