# Generated by Django 3.2.18 on 2023-12-29 00:00

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20231229_0139"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="сid",
        ),
        migrations.AddField(
            model_name="category",
            name="cid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=10,
                max_length=20,
                prefix="cat",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("process", "Processing"),
                    ("delivered", "Delivered"),
                    ("shipped", "Shipped"),
                ],
                default="Processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("disabled", "Disabled"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("in_review", "In Review"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(
                choices=[
                    ("5", "★★★★★"),
                    ("1", "★✩✩✩✩"),
                    ("4", "★★★★✩"),
                    ("2", "★★✩✩✩"),
                    ("3", "★★★✩✩"),
                ],
                default=None,
            ),
        ),
    ]
