# Generated by Django 3.2.18 on 2023-12-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20231229_0406"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="cid",
            new_name="vid",
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("shipped", "Shipped"),
                    ("process", "Processing"),
                    ("delivered", "Delivered"),
                ],
                default="Processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("in_review", "In Review"),
                    ("disabled", "Disabled"),
                    ("published", "Published"),
                    ("draft", "Draft"),
                    ("rejected", "Rejected"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(
                choices=[
                    ("3", "★★★✩✩"),
                    ("2", "★★✩✩✩"),
                    ("5", "★★★★★"),
                    ("1", "★✩✩✩✩"),
                    ("4", "★★★★✩"),
                ],
                default=None,
            ),
        ),
    ]
