# Generated by Django 3.2.18 on 2024-01-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20240109_0408"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("process", "Processing"),
                    ("delivered", "Delivered"),
                    ("shipped", "Shipped"),
                ],
                default="Processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("rejected", "Rejected"),
                    ("disabled", "Disabled"),
                    ("in_review", "In Review"),
                    ("published", "Published"),
                    ("draft", "Draft"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
    ]
