# Generated by Django 3.2.18 on 2024-01-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_auto_20240110_2309"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("shipped", "Shipped"),
                    ("process", "Processing"),
                ],
                default="Processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_character",
            field=models.CharField(
                choices=[("USED", "used"), ("NEW", "new")], default="new", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("in_review", "In Review"),
                    ("draft", "Draft"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                    ("disabled", "Disabled"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="parameter_description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="parametrs",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
