# Generated by Django 3.2.18 on 2024-01-18 04:31

import ckeditor_uploader.fields
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_auto_20240118_0556"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="address",
            field=models.CharField(default="123 Main Street.", max_length=100),
        ),
        migrations.AddField(
            model_name="vendor",
            name="authentic_rating",
            field=models.CharField(default="100", max_length=100),
        ),
        migrations.AddField(
            model_name="vendor",
            name="chat_resp_time",
            field=models.CharField(default="100", max_length=100),
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact",
            field=models.CharField(default="+123 (456) 789", max_length=100),
        ),
        migrations.AddField(
            model_name="vendor",
            name="cover_image",
            field=models.ImageField(
                default="vendor.jpg", upload_to=core.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="days_return",
            field=models.CharField(default="100", max_length=100),
        ),
        migrations.AddField(
            model_name="vendor",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="I am am Amazing Vendor", null=True
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="shipping_on_time",
            field=models.CharField(default="100", max_length=100),
        ),
        migrations.AddField(
            model_name="vendor",
            name="warranty_period",
            field=models.CharField(default="100", max_length=100),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("shipped", "Shipped"),
                    ("process", "Processing"),
                    ("delivered", "Delivered"),
                ],
                default="Processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("in_review", "In Review"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("draft", "Draft"),
                    ("disabled", "Disabled"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="image",
            field=models.ImageField(
                default="vendor.jpg", upload_to=core.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="title",
            field=models.CharField(default="Nestify", max_length=100),
        ),
    ]
