# Generated by Django 3.2.18 on 2024-05-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_auto_20240516_1810"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorderitems",
            name="order",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("process", "Processing"),
                ],
                default="Processing",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("disabled", "Disabled"),
                    ("in_review", "In Review"),
                    ("draft", "Draft"),
                    ("rejected", "Rejected"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="CartOrder",
        ),
        migrations.DeleteModel(
            name="CartOrderItems",
        ),
    ]
