# Generated by Django 3.2.18 on 2024-05-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_auto_20240519_2337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_character",
            field=models.CharField(
                choices=[("USED", "used"), ("NEW", "new")], default="new", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("in_review", "In Review"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("draft", "Draft"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
    ]
