# Generated by Django 3.2.18 on 2024-05-24 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0004_alter_user_telephone"),
        ("core", "0027_auto_20240524_0706"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managers",
                to="userauths.manager",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("process", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="Processing",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("rejected", "Rejected"),
                    ("in_review", "In Review"),
                    ("disabled", "Disabled"),
                    ("published", "Published"),
                    ("draft", "Draft"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
    ]
