# Generated by Django 3.2.18 on 2024-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_auto_20240524_0821"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="address",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="authentic_rating",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="chat_resp_time",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="date",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="days_return",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="shipping_on_time",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="warranty_period",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("shipped", "Shipped"),
                    ("process", "Processing"),
                ],
                default="Processing",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In Review"),
                    ("disabled", "Disabled"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
