# Generated by Django 3.2.18 on 2024-05-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_auto_20240528_2241"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Tags",
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("rejected", "Rejected"),
                    ("in_review", "In Review"),
                    ("published", "Published"),
                    ("disabled", "Disabled"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="core.Tag"),
        ),
    ]
