# Generated by Django 3.2.18 on 2024-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_auto_20240528_2244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("shipped", "Shipped"),
                    ("process", "Processing"),
                ],
                default="Processing",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_character",
            field=models.CharField(
                choices=[("NEW", "new"), ("USED", "used")], default="new", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("in_review", "In Review"),
                    ("rejected", "Rejected"),
                    ("disabled", "Disabled"),
                    ("draft", "Draft"),
                    ("published", "Published"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tags", to="core.Tag"
            ),
        ),
    ]
