# Generated by Django 3.2.18 on 2024-06-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_auto_20240601_1938"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("rejected", "Rejected"),
                    ("in_review", "In Review"),
                    ("disabled", "Disabled"),
                    ("published", "Published"),
                    ("draft", "Draft"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
    ]
